(ns symautre.content-data
  (:require [symautre.doc :refer [doc]]
            [symautre.tools.core :as t]
            [symautre.doc :as doc]))

(def posts
  [
   
   {:id "df4cba34-6922-4aae-90ff-521f7886d3c9",
    :title "P%litics"
    :timestamp.unix 1701477884781, :timestamp #inst "2023-12-02T00:44:44.781-00:00", :content "", :author nil, :body ["1/2 the population believes 1/3 of the population experiences panic attacks because the other 1/2 does not exist"]}
   
   {:id "88ce61f0-f8f9-4bca-a5ca-d85464e6e7ca", :timestamp.unix 1701096360237, :timestamp #inst "2023-11-27T14:46:00.237-00:00",
    :content "",
    :author nil,
    :title "Full Digital Anvilist",
    :body [[:img {:style {:max-width "20%"}, :src "https://media.tenor.com/wE_qxJqpxj0AAAAd/nether-portal-minecraft.gif"}] "ambient barks transduce the other\n& all the nites are obsidian\nlet's liquid speech for whiles\nwould this breach blink across ports enveloped in toilet horizons\nrooks crows ravens dogs\ntaste the blank memory of void on superzero shawties  \nbloodruns & foam obliviated in entropy edge"]}
   
   {:id "e01b5386-9450-4a7e-b063-c6c05d8b3b03", :timestamp.unix 1701096360237, :timestamp #inst "2023-11-27T14:46:00.237-00:00", :content "", :author nil, :title "Data vs Morph", :body [[:iframe {:src "https://www.youtube.com/embed/p19PzA5HauY", :title "YouTube video player", :frameborder "0", :allow "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share", :allowfullscreen true}] "to my knowledge all these systems implicitly or explicitly rely on an ordered sequence of actions. \nnow writing a transformation that converts these actionLogs to each other will buy you any database you want." "the thought process did not incorporate an intermediary datastructure such as JSON or EDN. so it was mostly HTTP POST & PUT requests directly mapping to storage places in tables.\n\nContent-Type: application/x-www-form-urlencoded" "with Algebra, there are multiple Voids:\nQualified Voids (Null fields) which are necessarily morphological nothings\nthere be exposure to Isomorphic indistinguishability\n(abstract walls which are ultimately the column names)\n\nwhile with pure data, types are merely symbolic links." "moving away from Tables is to go against Types & Law enforcement which scale clunkily with platonic data. \nAlgebra's simplicity is walled so: \nMatter Data |-> Algebra Morph\ngoing backwards means:\nAlgebra Morph -> Matter [Data Data]" "the dataAtom model of relationalDatabases doesn't make sense to me. since you usually get your data in document form anyway, it requires a funny conversion from document form to SQL insert form where you take each keyvalue in a document and put the value under the correct column!" "so types should be no different than a foreign key, and therefore also data.\none may need those Algebraic sophistries for other purposes such as reification of abstract computers and memory cells. but that's more a physicist's or psychoanalyst's problem."]}
   {:id "2d40535d-5dfa-4408-971f-d0d14aef3f9a", :timestamp.unix 1701096360237, :timestamp #inst "2023-11-27T14:46:00.237-00:00", :content "", :author nil, :title "blind", :body [[:img {:src "https://i.gifer.com/LWV6.gif"}] "as it began playing its blankett horizon memoryCell over the earth, dark side of plat∅'s sunset broke through its mind. it had let itself go with a synthetic invitation. it took up the symbol 𓏏 from afar & entered its fading smile as the EastWest Computer crashed." "truth had been apparent. walking right among the corrupt faction, no place to hide in this wealthy party. the wellrespected ophthalmologist  was an Al-Qaeda financier! obviously. who would've so much need for homegrown morphine? who would set the exchange rate of pain?" "the guests take a red crab apart at every joint. this cancer, not model but cork of all, is about to bust open an exit channel in its wake. it was is a simple flex of dignity for  the charitable upperclass, to pretend not to care one bit about the murder market." "it could stomach neither the food nor the scenery. it knew the neurologist was stepped away. mindfog was just two cool, something would ignite it, a hysteric reaction perhaps? it felt a pressure carefuly creeping up its left leg. sexual freeze. sexual frisk." "\"I love information. This is our sweetness and light.  It's a fuckall wonder. And we have meaning in the world. People eat and sleep in  the shadow of what we do. But at the same time, what?\"" "there is a cineme i njoyed, i nmember, in which The Kork becomes the dynamic unit of kapitalCurrency." "crab must have been consumed. its focus blinked across the party, memory gate to memory gate, scanning for information in unmeasured tempo. it had to remember this past it died in in every single sexual event.\n\na fictive concubine blanket to brush over the strata of fossil-fate" "\"I understand\"\n\"what was the message mr. gardner\"\n\"now get this huhnkey you go tell raphael that i ain't taking no jive from no western-union messenger, you tell that asshole [...]\"" "it knew there be conversations, through that frameKing, that oblivion edge of a memory port. that quantum nowhere, how they communicate. sentiences, unconscious of their relaying activity, oblivious to unconscious memory. eu philosophy was a petite-bourgoise ficKtivity." "yes somewhere someone, looking through the warped frames, someone reading Sartre, someone discussing Sim∅ne Beau Voir. all this french bullshit the agents of biopolitics flush down the Sophisticated's curious holes." "they needed information for Al-Qaeda. whole trees and org charts. dermatological log of indexfinger mazes. yes they needed it. it was not a matter of desire. it was very needed. so much necessity blinded them to french stalinist theatrics.\nthe cork was alway the same:\nرأس الع\n"]}
   ])

